include Makefile.prj.inc
include ../Makefile.com.inc
include ../Makefile.exe.inc

.PHONY: default
default: run-basic

run-basic: all
	@echo "------------- running basic tests -------------"
	$(BINDIR)/hex-test
